site_name: Contact Identity Tracker
site_description: The sole purpose of this extension is to keep a history of contact ID and external identfier that would otherwise be destroyed when merging duplicates
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.identitytracker

theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Configuration': configuration.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
